### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by ayyrickay** [Love-and-logic/urlshorty#30]
No rush on this, but to make things easier with deployment and hardcoded instances of `localhost` and the database URI, try using a tool like [node-foreman](https://github.com/strongloop/node-foreman) which allows you to use environment variables (a `.env` file)

For now, focus on functionality. It's fine if you demo the app on localhost!

**Comment by ayyrickay** [comment]
I hope all is well!
We made some attempts to push our app into the Heroku master. Some issues that came up was setting up buildpacks.

There were two attempts made-- to set Heroku's official Nodejs buildpack, and to set a custom buildpack referencing https://github.com/love-and-logic/urlshorty.git

For the official Node.js buildpack, the error message said that package.json was not at the application root. I am confused with this statement because I copied over the package.json file from urlshorty's server directory, into urlshorty's root folder.

For referencing a buildpack using the urlshorty github slug, some long bash messaged showed. Not too sure what it means.

```
Here are the error logs:
pushing official Node.js buildpack
git push heroku master
Counting objects: 281, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (244/244), done.
Writing objects: 100% (281/281), 63.19 KiB | 0 bytes/s, done.
Total 281 (delta 97), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> App not compatible with buildpack: https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/nodejs.tgz
remote:        Node.js: package.json not found in application root
remote:
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to quiet-sands-69707.
remote:
To https://git.heroku.com/quiet-sands-69707.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/quiet-sands-69707.git'

pushing with reference to urlshorty repo
git push heroku master
Counting objects: 281, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (244/244), done.
Writing objects: 100% (281/281), 63.19 KiB | 0 bytes/s, done.
Total 281 (delta 97), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> App not compatible with buildpack: https://github.com/love-and-logic/urlshorty.git
remote:        bash: /app/tmp/buildpacks/f80b45f268ab1d076104827bf3c3860ca52b06e1a0eb13df83b8a82ca7b4c19169fb7b209fbd701e1feaf24652f3676d28daae676c3bab48cc3371d0704dfae6/bin/detect: No such file or directory
remote:
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to quiet-sands-69707.
remote:
To https://git.heroku.com/quiet-sands-69707.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/quiet-sands-69707.git'
```

**Comment by ayyrickay** [comment]
@Love-and-logic @vanwars As you're seeing, heroku expects your package.json (and package.lock.json, and Profile) to be in the root directory. So you can move them out of the server folder and into the base of the repository (alongside where your gitignore would be.)

Run another `npm install` at the top level and ensure that everything is working, and in your package.json you can just create a start script that runs `node server/app.js`

**Comment by Love-and-logic** [comment]
Update--
With Procfile + package.json on the root repo, here is the log

```
$ git push heroku master
Counting objects: 281, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (244/244), done.
Writing objects: 100% (281/281), 63.19 KiB | 0 bytes/s, done.
Total 281 (delta 97), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> App not compatible with buildpack: https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/nodejs.tgz
remote:        Node.js: package.json not found in application root
remote:
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to quiet-sands-69707.
remote:
To https://git.heroku.com/quiet-sands-69707.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/quiet-sands-69707.git'
```

**Comment by Love-and-logic** [comment]
@ayyrickay @vanwars 
Update--
When running steps from * from above comment

- ran ```heroku buildpacks:remove heroku/nodejs```
- ran ```heroku buildpacks:set https://github.com/love-and-logic/urlshorty.git -a quiet-sands-69707```
- ran ```git push heroku master```

Report:
```
$ git push heroku master
Counting objects: 281, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (244/244), done.
Writing objects: 100% (281/281), 63.19 KiB | 0 bytes/s, done.
Total 281 (delta 97), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> App not compatible with buildpack: https://github.com/love-and-logic/urlshorty.git
remote:        bash: /app/tmp/buildpacks/f80b45f268ab1d076104827bf3c3860ca52b06e1a0eb13df83b8a82ca7b4c19169fb7b209fbd701e1feaf24652f3676d28daae676c3bab48cc3371d0704dfae6/bin/detect: No such file or directory
remote:
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to quiet-sands-69707.
remote:
To https://git.heroku.com/quiet-sands-69707.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/quiet-sands-69707.git'
````

**Comment by Love-and-logic** [comment]
Update--
Builds successful, still running into application errors. 
Current ```heroku logs``` show:

```
$ heroku logs
2018-05-23T04:59:46.670741+00:00 app[web.1]: at runCallback (timers.js:810:20)
2018-05-23T04:59:46.670742+00:00 app[web.1]: at tryOnImmediate (timers.js:768:5)
2018-05-23T04:59:46.670743+00:00 app[web.1]: at processImmediate [as _immediateCallback] (timers.js:745:5)
2018-05-23T04:59:46.679841+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2018-05-23T04:59:46.680263+00:00 app[web.1]: npm ERR! errno 1
2018-05-23T04:59:46.681633+00:00 app[web.1]: npm ERR! server@1.0.0 start: `node server/app.js`
2018-05-23T04:59:46.681636+00:00 app[web.1]: npm ERR! Exit status 1
2018-05-23T04:59:46.681637+00:00 app[web.1]: npm ERR!
2018-05-23T04:59:46.681639+00:00 app[web.1]: npm ERR! Failed at the server@1.0.0 start script.
2018-05-23T04:59:46.681686+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-05-23T04:59:46.687438+00:00 app[web.1]:
2018-05-23T04:59:46.687572+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2018-05-23T04:59:46.687654+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2018-05-23T04_59_46_682Z-debug.log
2018-05-23T04:59:46.675837+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/favicon.ico" host=mmart162-final-project.herokuapp.com request_id=03f1a9c1-057a-43c3-8328-4a4c4cf4de63 fwd="209.129.168.20" dyno=web.1 connect=0ms service=29ms status=503 bytes=0 protocol=https
2018-05-23T04:59:46.760322+00:00 heroku[web.1]: State changed from up to crashed
2018-05-23T04:59:46.743974+00:00 heroku[web.1]: Process exited with status 1
2018-05-23T04:59:50.115923+00:00 heroku[web.1]: State changed from crashed to starting
2018-05-23T05:14:34.300511+00:00 heroku[web.1]: State changed from crashed to starting
2018-05-23T05:14:43.121273+00:00 heroku[web.1]: Starting process with command `npm start`
2018-05-23T05:14:46.008825+00:00 app[web.1]:
2018-05-23T05:14:46.008845+00:00 app[web.1]: > server@1.0.0 start /app
2018-05-23T05:14:46.008847+00:00 app[web.1]: > node server/app.js
2018-05-23T05:14:46.008849+00:00 app[web.1]:
2018-05-23T05:14:47.666080+00:00 heroku[web.1]: State changed from starting to up
2018-05-23T05:46:52.002695+00:00 heroku[web.1]: Idling
2018-05-23T05:46:52.004718+00:00 heroku[web.1]: State changed from up to down
2018-05-23T05:46:52.935761+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2018-05-23T05:46:53.047482+00:00 heroku[web.1]: Process exited with status 143
2018-05-24T20:13:21.000000+00:00 app[api]: Build started by user ejatbcc@gmail.com
2018-05-24T20:13:38.666330+00:00 app[api]: Deploy 4913cde5 by user ejatbcc@gmail.com
2018-05-24T20:13:38.666330+00:00 app[api]: Release v25 created by user ejatbcc@gmail.com
2018-05-24T20:13:38.000000+00:00 app[api]: Build succeeded
2018-05-24T20:13:40.097844+00:00 heroku[web.1]: State changed from down to starting
2018-05-24T20:13:43.660058+00:00 heroku[web.1]: Starting process with command `npm start`
2018-05-24T20:13:45.913215+00:00 app[web.1]:
2018-05-24T20:13:45.913240+00:00 app[web.1]: > server@1.0.0 start /app
2018-05-24T20:13:45.913242+00:00 app[web.1]: > node server/app.js
2018-05-24T20:13:45.913243+00:00 app[web.1]:
2018-05-24T20:13:47.413976+00:00 heroku[web.1]: State changed from starting to up
2018-05-24T20:13:48.021252+00:00 app[web.1]: {}
2018-05-24T20:13:48.034532+00:00 app[web.1]: events.js:183
2018-05-24T20:13:48.034535+00:00 app[web.1]: throw er; // Unhandled 'error' event
2018-05-24T20:13:48.034536+00:00 app[web.1]: ^
2018-05-24T20:13:48.034538+00:00 app[web.1]:
2018-05-24T20:13:48.034539+00:00 app[web.1]: TypeError: Cannot read property 'url' of null
2018-05-24T20:13:48.034541+00:00 app[web.1]: at /app/server/routes/index.js:40:32
2018-05-24T20:13:48.034581+00:00 app[web.1]: at /app/node_modules/mongoose/lib/model.js:4177:16
2018-05-24T20:13:48.034583+00:00 app[web.1]: at model.Query.Query._completeOne (/app/node_modules/mongoose/lib/query.js:1478:12)
2018-05-24T20:13:48.034584+00:00 app[web.1]: at Immediate.Query.base.findOne.call (/app/node_modules/mongoose/lib/query.js:1532:10)
2018-05-24T20:13:48.034586+00:00 app[web.1]: at Immediate._onImmediate (/app/node_modules/mquery/lib/utils.js:119:16)
2018-05-24T20:13:48.034587+00:00 app[web.1]: at runCallback (timers.js:810:20)
2018-05-24T20:13:48.034589+00:00 app[web.1]: at tryOnImmediate (timers.js:768:5)
2018-05-24T20:13:48.034591+00:00 app[web.1]: at processImmediate [as _immediateCallback] (timers.js:745:5)
2018-05-24T20:13:48.041352+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2018-05-24T20:13:48.041685+00:00 app[web.1]: npm ERR! errno 1
2018-05-24T20:13:48.042819+00:00 app[web.1]: npm ERR! server@1.0.0 start: `node server/app.js`
2018-05-24T20:13:48.042935+00:00 app[web.1]: npm ERR! Exit status 1
2018-05-24T20:13:48.043150+00:00 app[web.1]: npm ERR!
2018-05-24T20:13:48.043281+00:00 app[web.1]: npm ERR! Failed at the server@1.0.0 start script.
2018-05-24T20:13:48.043407+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-05-24T20:13:48.047104+00:00 app[web.1]:
2018-05-24T20:13:48.047239+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2018-05-24T20:13:48.047316+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2018-05-24T20_13_48_044Z-debug.log
2018-05-24T20:13:48.036481+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/" host=mmart162-final-project.herokuapp.com request_id=c27cdb47-2033-4269-aeb1-34ee0e202aea fwd="73.71.228.109" dyno=web.1 connect=1ms service=27ms status=503 bytes=0 protocol=https
2018-05-24T20:13:48.149601+00:00 heroku[web.1]: State changed from up to crashed
2018-05-24T20:13:48.152896+00:00 heroku[web.1]: State changed from crashed to starting
2018-05-24T20:13:48.106483+00:00 heroku[web.1]: Process exited with status 1
2018-05-24T20:13:53.130220+00:00 heroku[web.1]: Starting process with command `npm start`
2018-05-24T20:13:56.162093+00:00 app[web.1]:
2018-05-24T20:13:56.162131+00:00 app[web.1]: > server@1.0.0 start /app
2018-05-24T20:13:56.162133+00:00 app[web.1]: > node server/app.js
2018-05-24T20:13:56.162135+00:00 app[web.1]:
2018-05-24T20:13:57.813688+00:00 heroku[web.1]: State changed from starting to up
2018-05-24T20:13:59.675105+00:00 app[web.1]: {}
2018-05-24T20:13:59.697041+00:00 app[web.1]: events.js:183
2018-05-24T20:13:59.697046+00:00 app[web.1]: throw er; // Unhandled 'error' event
2018-05-24T20:13:59.697048+00:00 app[web.1]: ^
2018-05-24T20:13:59.697049+00:00 app[web.1]:
2018-05-24T20:13:59.697051+00:00 app[web.1]: TypeError: Cannot read property 'url' of null
2018-05-24T20:13:59.697052+00:00 app[web.1]: at /app/server/routes/index.js:40:32
2018-05-24T20:13:59.697054+00:00 app[web.1]: at /app/node_modules/mongoose/lib/model.js:4177:16
2018-05-24T20:13:59.697056+00:00 app[web.1]: at model.Query.Query._completeOne (/app/node_modules/mongoose/lib/query.js:1478:12)
2018-05-24T20:13:59.697058+00:00 app[web.1]: at Immediate.Query.base.findOne.call (/app/node_modules/mongoose/lib/query.js:1532:10)
2018-05-24T20:13:59.697060+00:00 app[web.1]: at Immediate._onImmediate (/app/node_modules/mquery/lib/utils.js:119:16)
2018-05-24T20:13:59.697062+00:00 app[web.1]: at runCallback (timers.js:810:20)
2018-05-24T20:13:59.697064+00:00 app[web.1]: at tryOnImmediate (timers.js:768:5)
2018-05-24T20:13:59.697065+00:00 app[web.1]: at processImmediate [as _immediateCallback] (timers.js:745:5)
2018-05-24T20:13:59.711801+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2018-05-24T20:13:59.712373+00:00 app[web.1]: npm ERR! errno 1
2018-05-24T20:13:59.714085+00:00 app[web.1]: npm ERR! server@1.0.0 start: `node server/app.js`
2018-05-24T20:13:59.714372+00:00 app[web.1]: npm ERR! Exit status 1
2018-05-24T20:13:59.714717+00:00 app[web.1]: npm ERR!
2018-05-24T20:13:59.714982+00:00 app[web.1]: npm ERR! Failed at the server@1.0.0 start script.
2018-05-24T20:13:59.715247+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-05-24T20:13:59.723700+00:00 app[web.1]:
2018-05-24T20:13:59.724012+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2018-05-24T20:13:59.724237+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2018-05-24T20_13_59_717Z-debug.log
2018-05-24T20:13:59.827672+00:00 heroku[web.1]: State changed from up to crashed
2018-05-24T20:13:59.707712+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/favicon.ico" host=mmart162-final-project.herokuapp.com request_id=448c4e0b-ed18-4eda-a983-36a149b184fc fwd="73.71.228.109" dyno=web.1 connect=0ms service=48ms status=503 bytes=0 protocol=https
2018-05-24T20:13:59.800264+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by Love-and-logic** [comment]
Team update -- woohoo! 
We got server response code to work: https://mmart162-final-project.herokuapp.com/

Working on Javascript scripts atm.

**Comment by ehidinborbon** [comment]
deployed! https://mmart162-final-project.herokuapp.com/
